from enum import Enum


class PublisherState(str, Enum):
    DISCONNECTED = "DISCONNECTED"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    CHANNEL_OPEN = "CHANNEL_OPEN"
    CONFIRM_ENABLED = "CONFIRM_ENABLED"
    QUEUE_DECLARED = "QUEUE_DECLARED"
    READY = "READY"
    RECONNECTING = "RECONNECTING"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
